let warmHugs = "Hi, I\'m Olaf and I like warm hugs.";
console.log(warmHugs.toUpperCase());
console.log(warmHugs.replace("like", "love"));
let beenImpaled = "Oh, look at that. I\'ve been impaled.";
console.log(beenImpaled.indexOf("I've been impaled."));
let dotDotDot = "...";
let skullBones = "I don't have a skull" + dotDotDot + " or bones.";
console.log(Math.PI);
let randomNumber = Math.random();
randomNumber *= 3;
randomNumber = Math.floor(randomNumber);
randomNumber++;
console.log(randomNumber);